// Code generated by ent, DO NOT EDIT.

package entgen

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/shunwuse/go-hris/ent/entgen/approval"
	"github.com/shunwuse/go-hris/ent/entgen/user"
	"github.com/shunwuse/go-hris/internal/constants"
)

// ApprovalCreate is the builder for creating a Approval entity.
type ApprovalCreate struct {
	config
	mutation *ApprovalMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *ApprovalCreate) SetCreatedAt(v time.Time) *ApprovalCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ApprovalCreate) SetNillableCreatedAt(v *time.Time) *ApprovalCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ApprovalCreate) SetUpdatedAt(v time.Time) *ApprovalCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ApprovalCreate) SetNillableUpdatedAt(v *time.Time) *ApprovalCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *ApprovalCreate) SetDeletedAt(v time.Time) *ApprovalCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *ApprovalCreate) SetNillableDeletedAt(v *time.Time) *ApprovalCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *ApprovalCreate) SetStatus(v constants.ApprovalStatus) *ApprovalCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetCreatorID sets the "creator_id" field.
func (_c *ApprovalCreate) SetCreatorID(v uint) *ApprovalCreate {
	_c.mutation.SetCreatorID(v)
	return _c
}

// SetApproverID sets the "approver_id" field.
func (_c *ApprovalCreate) SetApproverID(v uint) *ApprovalCreate {
	_c.mutation.SetApproverID(v)
	return _c
}

// SetNillableApproverID sets the "approver_id" field if the given value is not nil.
func (_c *ApprovalCreate) SetNillableApproverID(v *uint) *ApprovalCreate {
	if v != nil {
		_c.SetApproverID(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ApprovalCreate) SetID(v uint) *ApprovalCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetCreator sets the "creator" edge to the User entity.
func (_c *ApprovalCreate) SetCreator(v *User) *ApprovalCreate {
	return _c.SetCreatorID(v.ID)
}

// SetApprover sets the "approver" edge to the User entity.
func (_c *ApprovalCreate) SetApprover(v *User) *ApprovalCreate {
	return _c.SetApproverID(v.ID)
}

// Mutation returns the ApprovalMutation object of the builder.
func (_c *ApprovalCreate) Mutation() *ApprovalMutation {
	return _c.mutation
}

// Save creates the Approval in the database.
func (_c *ApprovalCreate) Save(ctx context.Context) (*Approval, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ApprovalCreate) SaveX(ctx context.Context) *Approval {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ApprovalCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ApprovalCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ApprovalCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := approval.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := approval.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ApprovalCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`entgen: missing required field "Approval.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`entgen: missing required field "Approval.updated_at"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`entgen: missing required field "Approval.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := approval.StatusValidator(string(v)); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`entgen: validator failed for field "Approval.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatorID(); !ok {
		return &ValidationError{Name: "creator_id", err: errors.New(`entgen: missing required field "Approval.creator_id"`)}
	}
	if v, ok := _c.mutation.CreatorID(); ok {
		if err := approval.CreatorIDValidator(v); err != nil {
			return &ValidationError{Name: "creator_id", err: fmt.Errorf(`entgen: validator failed for field "Approval.creator_id": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ApproverID(); ok {
		if err := approval.ApproverIDValidator(v); err != nil {
			return &ValidationError{Name: "approver_id", err: fmt.Errorf(`entgen: validator failed for field "Approval.approver_id": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := approval.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`entgen: validator failed for field "Approval.id": %w`, err)}
		}
	}
	if len(_c.mutation.CreatorIDs()) == 0 {
		return &ValidationError{Name: "creator", err: errors.New(`entgen: missing required edge "Approval.creator"`)}
	}
	return nil
}

func (_c *ApprovalCreate) sqlSave(ctx context.Context) (*Approval, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ApprovalCreate) createSpec() (*Approval, *sqlgraph.CreateSpec) {
	var (
		_node = &Approval{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(approval.Table, sqlgraph.NewFieldSpec(approval.FieldID, field.TypeUint))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(approval.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(approval.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(approval.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(approval.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if nodes := _c.mutation.CreatorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   approval.CreatorTable,
			Columns: []string{approval.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.CreatorID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ApproverIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   approval.ApproverTable,
			Columns: []string{approval.ApproverColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ApproverID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ApprovalCreateBulk is the builder for creating many Approval entities in bulk.
type ApprovalCreateBulk struct {
	config
	err      error
	builders []*ApprovalCreate
}

// Save creates the Approval entities in the database.
func (_c *ApprovalCreateBulk) Save(ctx context.Context) ([]*Approval, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Approval, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ApprovalMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ApprovalCreateBulk) SaveX(ctx context.Context) []*Approval {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ApprovalCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ApprovalCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
