// Code generated by ent, DO NOT EDIT.

package entgen

import (
	"time"

	"github.com/shunwuse/go-hris/ent/entgen/approval"
	"github.com/shunwuse/go-hris/ent/entgen/password"
	"github.com/shunwuse/go-hris/ent/entgen/permission"
	"github.com/shunwuse/go-hris/ent/entgen/role"
	"github.com/shunwuse/go-hris/ent/entgen/rolepermission"
	"github.com/shunwuse/go-hris/ent/entgen/user"
	"github.com/shunwuse/go-hris/ent/entgen/userrole"
	"github.com/shunwuse/go-hris/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	approvalMixin := schema.Approval{}.Mixin()
	approvalMixinFields0 := approvalMixin[0].Fields()
	_ = approvalMixinFields0
	approvalMixinFields1 := approvalMixin[1].Fields()
	_ = approvalMixinFields1
	approvalFields := schema.Approval{}.Fields()
	_ = approvalFields
	// approvalDescCreatedAt is the schema descriptor for created_at field.
	approvalDescCreatedAt := approvalMixinFields1[0].Descriptor()
	// approval.DefaultCreatedAt holds the default value on creation for the created_at field.
	approval.DefaultCreatedAt = approvalDescCreatedAt.Default.(func() time.Time)
	// approvalDescUpdatedAt is the schema descriptor for updated_at field.
	approvalDescUpdatedAt := approvalMixinFields1[1].Descriptor()
	// approval.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	approval.DefaultUpdatedAt = approvalDescUpdatedAt.Default.(func() time.Time)
	// approval.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	approval.UpdateDefaultUpdatedAt = approvalDescUpdatedAt.UpdateDefault.(func() time.Time)
	// approvalDescStatus is the schema descriptor for status field.
	approvalDescStatus := approvalFields[0].Descriptor()
	// approval.StatusValidator is a validator for the "status" field. It is called by the builders before save.
	approval.StatusValidator = approvalDescStatus.Validators[0].(func(string) error)
	// approvalDescCreatorID is the schema descriptor for creator_id field.
	approvalDescCreatorID := approvalFields[1].Descriptor()
	// approval.CreatorIDValidator is a validator for the "creator_id" field. It is called by the builders before save.
	approval.CreatorIDValidator = approvalDescCreatorID.Validators[0].(func(uint) error)
	// approvalDescApproverID is the schema descriptor for approver_id field.
	approvalDescApproverID := approvalFields[2].Descriptor()
	// approval.ApproverIDValidator is a validator for the "approver_id" field. It is called by the builders before save.
	approval.ApproverIDValidator = approvalDescApproverID.Validators[0].(func(uint) error)
	// approvalDescID is the schema descriptor for id field.
	approvalDescID := approvalMixinFields0[0].Descriptor()
	// approval.IDValidator is a validator for the "id" field. It is called by the builders before save.
	approval.IDValidator = approvalDescID.Validators[0].(func(uint) error)
	passwordMixin := schema.Password{}.Mixin()
	passwordMixinFields0 := passwordMixin[0].Fields()
	_ = passwordMixinFields0
	passwordMixinFields1 := passwordMixin[1].Fields()
	_ = passwordMixinFields1
	passwordFields := schema.Password{}.Fields()
	_ = passwordFields
	// passwordDescCreatedAt is the schema descriptor for created_at field.
	passwordDescCreatedAt := passwordMixinFields1[0].Descriptor()
	// password.DefaultCreatedAt holds the default value on creation for the created_at field.
	password.DefaultCreatedAt = passwordDescCreatedAt.Default.(func() time.Time)
	// passwordDescUpdatedAt is the schema descriptor for updated_at field.
	passwordDescUpdatedAt := passwordMixinFields1[1].Descriptor()
	// password.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	password.DefaultUpdatedAt = passwordDescUpdatedAt.Default.(func() time.Time)
	// password.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	password.UpdateDefaultUpdatedAt = passwordDescUpdatedAt.UpdateDefault.(func() time.Time)
	// passwordDescUserID is the schema descriptor for user_id field.
	passwordDescUserID := passwordFields[0].Descriptor()
	// password.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	password.UserIDValidator = passwordDescUserID.Validators[0].(func(uint) error)
	// passwordDescHash is the schema descriptor for hash field.
	passwordDescHash := passwordFields[1].Descriptor()
	// password.HashValidator is a validator for the "hash" field. It is called by the builders before save.
	password.HashValidator = passwordDescHash.Validators[0].(func(string) error)
	// passwordDescID is the schema descriptor for id field.
	passwordDescID := passwordMixinFields0[0].Descriptor()
	// password.IDValidator is a validator for the "id" field. It is called by the builders before save.
	password.IDValidator = passwordDescID.Validators[0].(func(uint) error)
	permissionMixin := schema.Permission{}.Mixin()
	permissionMixinFields0 := permissionMixin[0].Fields()
	_ = permissionMixinFields0
	permissionMixinFields1 := permissionMixin[1].Fields()
	_ = permissionMixinFields1
	permissionFields := schema.Permission{}.Fields()
	_ = permissionFields
	// permissionDescCreatedAt is the schema descriptor for created_at field.
	permissionDescCreatedAt := permissionMixinFields1[0].Descriptor()
	// permission.DefaultCreatedAt holds the default value on creation for the created_at field.
	permission.DefaultCreatedAt = permissionDescCreatedAt.Default.(func() time.Time)
	// permissionDescUpdatedAt is the schema descriptor for updated_at field.
	permissionDescUpdatedAt := permissionMixinFields1[1].Descriptor()
	// permission.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	permission.DefaultUpdatedAt = permissionDescUpdatedAt.Default.(func() time.Time)
	// permission.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	permission.UpdateDefaultUpdatedAt = permissionDescUpdatedAt.UpdateDefault.(func() time.Time)
	// permissionDescDescription is the schema descriptor for description field.
	permissionDescDescription := permissionFields[0].Descriptor()
	// permission.DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	permission.DescriptionValidator = permissionDescDescription.Validators[0].(func(string) error)
	// permissionDescID is the schema descriptor for id field.
	permissionDescID := permissionMixinFields0[0].Descriptor()
	// permission.IDValidator is a validator for the "id" field. It is called by the builders before save.
	permission.IDValidator = permissionDescID.Validators[0].(func(uint) error)
	roleMixin := schema.Role{}.Mixin()
	roleMixinFields0 := roleMixin[0].Fields()
	_ = roleMixinFields0
	roleMixinFields1 := roleMixin[1].Fields()
	_ = roleMixinFields1
	roleFields := schema.Role{}.Fields()
	_ = roleFields
	// roleDescCreatedAt is the schema descriptor for created_at field.
	roleDescCreatedAt := roleMixinFields1[0].Descriptor()
	// role.DefaultCreatedAt holds the default value on creation for the created_at field.
	role.DefaultCreatedAt = roleDescCreatedAt.Default.(func() time.Time)
	// roleDescUpdatedAt is the schema descriptor for updated_at field.
	roleDescUpdatedAt := roleMixinFields1[1].Descriptor()
	// role.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	role.DefaultUpdatedAt = roleDescUpdatedAt.Default.(func() time.Time)
	// role.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	role.UpdateDefaultUpdatedAt = roleDescUpdatedAt.UpdateDefault.(func() time.Time)
	// roleDescName is the schema descriptor for name field.
	roleDescName := roleFields[0].Descriptor()
	// role.NameValidator is a validator for the "name" field. It is called by the builders before save.
	role.NameValidator = roleDescName.Validators[0].(func(string) error)
	// roleDescID is the schema descriptor for id field.
	roleDescID := roleMixinFields0[0].Descriptor()
	// role.IDValidator is a validator for the "id" field. It is called by the builders before save.
	role.IDValidator = roleDescID.Validators[0].(func(uint) error)
	rolepermissionMixin := schema.RolePermission{}.Mixin()
	rolepermissionMixinFields0 := rolepermissionMixin[0].Fields()
	_ = rolepermissionMixinFields0
	rolepermissionMixinFields1 := rolepermissionMixin[1].Fields()
	_ = rolepermissionMixinFields1
	rolepermissionFields := schema.RolePermission{}.Fields()
	_ = rolepermissionFields
	// rolepermissionDescCreatedAt is the schema descriptor for created_at field.
	rolepermissionDescCreatedAt := rolepermissionMixinFields1[0].Descriptor()
	// rolepermission.DefaultCreatedAt holds the default value on creation for the created_at field.
	rolepermission.DefaultCreatedAt = rolepermissionDescCreatedAt.Default.(func() time.Time)
	// rolepermissionDescUpdatedAt is the schema descriptor for updated_at field.
	rolepermissionDescUpdatedAt := rolepermissionMixinFields1[1].Descriptor()
	// rolepermission.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	rolepermission.DefaultUpdatedAt = rolepermissionDescUpdatedAt.Default.(func() time.Time)
	// rolepermission.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	rolepermission.UpdateDefaultUpdatedAt = rolepermissionDescUpdatedAt.UpdateDefault.(func() time.Time)
	// rolepermissionDescRoleID is the schema descriptor for role_id field.
	rolepermissionDescRoleID := rolepermissionFields[0].Descriptor()
	// rolepermission.RoleIDValidator is a validator for the "role_id" field. It is called by the builders before save.
	rolepermission.RoleIDValidator = rolepermissionDescRoleID.Validators[0].(func(uint) error)
	// rolepermissionDescPermissionID is the schema descriptor for permission_id field.
	rolepermissionDescPermissionID := rolepermissionFields[1].Descriptor()
	// rolepermission.PermissionIDValidator is a validator for the "permission_id" field. It is called by the builders before save.
	rolepermission.PermissionIDValidator = rolepermissionDescPermissionID.Validators[0].(func(uint) error)
	// rolepermissionDescID is the schema descriptor for id field.
	rolepermissionDescID := rolepermissionMixinFields0[0].Descriptor()
	// rolepermission.IDValidator is a validator for the "id" field. It is called by the builders before save.
	rolepermission.IDValidator = rolepermissionDescID.Validators[0].(func(uint) error)
	userMixin := schema.User{}.Mixin()
	userMixinFields0 := userMixin[0].Fields()
	_ = userMixinFields0
	userMixinFields1 := userMixin[1].Fields()
	_ = userMixinFields1
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userMixinFields1[0].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userMixinFields1[1].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescUsername is the schema descriptor for username field.
	userDescUsername := userFields[0].Descriptor()
	// user.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	user.UsernameValidator = userDescUsername.Validators[0].(func(string) error)
	// userDescName is the schema descriptor for name field.
	userDescName := userFields[1].Descriptor()
	// user.NameValidator is a validator for the "name" field. It is called by the builders before save.
	user.NameValidator = userDescName.Validators[0].(func(string) error)
	// userDescID is the schema descriptor for id field.
	userDescID := userMixinFields0[0].Descriptor()
	// user.IDValidator is a validator for the "id" field. It is called by the builders before save.
	user.IDValidator = userDescID.Validators[0].(func(uint) error)
	userroleMixin := schema.UserRole{}.Mixin()
	userroleMixinFields0 := userroleMixin[0].Fields()
	_ = userroleMixinFields0
	userroleMixinFields1 := userroleMixin[1].Fields()
	_ = userroleMixinFields1
	userroleFields := schema.UserRole{}.Fields()
	_ = userroleFields
	// userroleDescCreatedAt is the schema descriptor for created_at field.
	userroleDescCreatedAt := userroleMixinFields1[0].Descriptor()
	// userrole.DefaultCreatedAt holds the default value on creation for the created_at field.
	userrole.DefaultCreatedAt = userroleDescCreatedAt.Default.(func() time.Time)
	// userroleDescUpdatedAt is the schema descriptor for updated_at field.
	userroleDescUpdatedAt := userroleMixinFields1[1].Descriptor()
	// userrole.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	userrole.DefaultUpdatedAt = userroleDescUpdatedAt.Default.(func() time.Time)
	// userrole.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	userrole.UpdateDefaultUpdatedAt = userroleDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userroleDescUserID is the schema descriptor for user_id field.
	userroleDescUserID := userroleFields[0].Descriptor()
	// userrole.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	userrole.UserIDValidator = userroleDescUserID.Validators[0].(func(uint) error)
	// userroleDescRoleID is the schema descriptor for role_id field.
	userroleDescRoleID := userroleFields[1].Descriptor()
	// userrole.RoleIDValidator is a validator for the "role_id" field. It is called by the builders before save.
	userrole.RoleIDValidator = userroleDescRoleID.Validators[0].(func(uint) error)
	// userroleDescID is the schema descriptor for id field.
	userroleDescID := userroleMixinFields0[0].Descriptor()
	// userrole.IDValidator is a validator for the "id" field. It is called by the builders before save.
	userrole.IDValidator = userroleDescID.Validators[0].(func(uint) error)
}
