services:
  postgres:
    image: postgres:15-alpine
    container_name: hris-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=hris
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - hris-network

  api:
    build:
      context: ..
      dockerfile: build/package/Dockerfile
    image: go-hris:latest
    container_name: hris-api
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      - APP_ENV=development
      - APP_SERVER_PORT=8080
      - APP_DB_HOST=postgres
    restart: unless-stopped
    networks:
      - hris-network

  worker:
    image: go-hris:latest
    container_name: hris-worker
    depends_on:
      - postgres
    command: ["./app-worker"]
    environment:
      - APP_ENV=development
      - APP_DB_HOST=postgres
    restart: unless-stopped
    networks:
      - hris-network

networks:
  hris-network:
    driver: bridge

volumes:
  postgres_data:
