// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/shunwuse/go-hris/internal/infra/alerter"
	"github.com/shunwuse/go-hris/internal/infra/cache"
	"github.com/shunwuse/go-hris/internal/infra/database"
	"github.com/shunwuse/go-hris/internal/infra/token"
	"github.com/shunwuse/go-hris/internal/pkg/logger"
	"github.com/shunwuse/go-hris/internal/queries"
	"github.com/shunwuse/go-hris/internal/repositories"
	"github.com/shunwuse/go-hris/internal/services"
	"github.com/shunwuse/go-hris/internal/worker/consumer"
	"github.com/shunwuse/go-hris/internal/worker/consumer/handlers"
	"github.com/shunwuse/go-hris/internal/worker/scheduler"
	"github.com/shunwuse/go-hris/internal/worker/scheduler/jobs"
)

// Injectors from wire.go:

func InitializeWorker(cfg *Config, log *logger.Logger) *Worker {
	config := &cfg.Database
	databaseDatabase := database.New(config, log)
	cacheConfig := &cfg.Cache
	cacheCache := cache.New(cacheConfig, log)
	infraAlerter := alerter.NewMultiAlerter(log)
	authConfig := &cfg.Auth
	transactor := database.NewTransactor(databaseDatabase)
	tokenService := token.New(authConfig, log, cacheCache)
	authRepository := repositories.NewAuthRepository(log, databaseDatabase)
	userRepository := repositories.NewUserRepository(log, databaseDatabase, cacheCache)
	roleRepository := repositories.NewRoleRepository(log, databaseDatabase, cacheCache)
	userIdentityReader := queries.NewUserIdentityReader(cacheCache, userRepository, roleRepository)
	authService := services.NewAuthService(authConfig, log, transactor, tokenService, authRepository, userIdentityReader)
	cleanupTokensJob := jobs.NewCleanupTokensJob(log, authService)
	cronJobs := jobs.NewCronJobs(cleanupTokensJob)
	schedulerScheduler := scheduler.NewScheduler(log, infraAlerter, cronJobs)
	cleanupTokensHandler := handlers.NewCleanupTokensHandler(log, authService)
	handlersHandlers := handlers.NewHandlers(cleanupTokensHandler)
	consumerConsumer := consumer.NewConsumer(log, handlersHandlers)
	worker := NewWorker(log, databaseDatabase, cacheCache, schedulerScheduler, consumerConsumer)
	return worker
}
