CREATE TABLE IF NOT EXISTS approvals (
    id SERIAL PRIMARY KEY,
    status TEXT NOT NULL,
    creator_id INTEGER NOT NULL,
    approver_id INTEGER,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP
);
