// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/shunwuse/go-hris/internal/http/controllers"
	"github.com/shunwuse/go-hris/internal/http/middlewares"
	"github.com/shunwuse/go-hris/internal/http/router"
	"github.com/shunwuse/go-hris/internal/http/routes"
	"github.com/shunwuse/go-hris/internal/infra/alerter"
	"github.com/shunwuse/go-hris/internal/infra/cache"
	"github.com/shunwuse/go-hris/internal/infra/database"
	"github.com/shunwuse/go-hris/internal/infra/idempotency"
	"github.com/shunwuse/go-hris/internal/infra/metrics"
	"github.com/shunwuse/go-hris/internal/infra/token"
	"github.com/shunwuse/go-hris/internal/pkg/logger"
	"github.com/shunwuse/go-hris/internal/queries"
	"github.com/shunwuse/go-hris/internal/repositories"
	"github.com/shunwuse/go-hris/internal/services"
)

// Injectors from wire.go:

func InitializeServer(cfg *Config, log *logger.Logger) *Server {
	config := &cfg.Database
	databaseDatabase := database.New(config, log)
	cacheConfig := &cfg.Cache
	cacheCache := cache.New(cacheConfig, log)
	corsMiddleware := middlewares.NewCORSMiddleware()
	traceMiddleware := middlewares.NewTraceMiddleware(log)
	metricsMetrics := metrics.New()
	metricsMiddleware := middlewares.NewMetricsMiddleware(metricsMetrics)
	requestLoggerMiddleware := middlewares.NewRequestLoggerMiddleware(log)
	infraAlerter := alerter.NewMultiAlerter(log)
	recoveryMiddleware := middlewares.NewRecoveryMiddleware(log, infraAlerter)
	serviceConfig := &cfg.Service
	manager := idempotency.New(log, cacheCache)
	idempotencyMiddleware := middlewares.NewIdempotencyMiddleware(serviceConfig, manager, log)
	exceptionMiddleware := middlewares.NewExceptionMiddleware(infraAlerter)
	commonMiddlewares := middlewares.NewCommonMiddlewares(corsMiddleware, traceMiddleware, metricsMiddleware, requestLoggerMiddleware, recoveryMiddleware, idempotencyMiddleware, exceptionMiddleware)
	profilerMiddleware := middlewares.NewProfilerMiddleware(serviceConfig)
	monitorRepository := repositories.NewMonitorRepository(log, databaseDatabase, cacheCache)
	monitorService := services.NewMonitorService(serviceConfig, log, monitorRepository)
	monitorController := controllers.NewMonitorController(log, monitorService)
	monitorRoute := routes.NewMonitorRoute(log, metricsMetrics, profilerMiddleware, monitorController)
	authConfig := &cfg.Auth
	transactor := database.NewTransactor(databaseDatabase)
	tokenService := token.New(authConfig, log, cacheCache)
	authRepository := repositories.NewAuthRepository(log, databaseDatabase)
	userRepository := repositories.NewUserRepository(log, databaseDatabase, cacheCache)
	roleRepository := repositories.NewRoleRepository(log, databaseDatabase, cacheCache)
	userIdentityReader := queries.NewUserIdentityReader(cacheCache, userRepository, roleRepository)
	authService := services.NewAuthService(authConfig, log, transactor, tokenService, authRepository, userIdentityReader)
	jwtMiddleware := middlewares.NewJWTMiddleware(log, authService)
	userService := services.NewUserService(log, transactor, userRepository, roleRepository, userIdentityReader)
	userController := controllers.NewUserController(log, userService)
	userRoute := routes.NewUserRoute(log, jwtMiddleware, userController)
	approvalRepository := repositories.NewApprovalRepository(log, databaseDatabase)
	approvalService := services.NewApprovalService(log, approvalRepository)
	approvalController := controllers.NewApprovalController(log, approvalService)
	approvalRoute := routes.NewApprovalRoute(log, jwtMiddleware, approvalController)
	authController := controllers.NewAuthController(log, authService)
	authRoute := routes.NewAuthRoute(log, jwtMiddleware, authController)
	routesRoutes := routes.NewRoutes(monitorRoute, userRoute, approvalRoute, authRoute)
	routerRouter := router.New(commonMiddlewares, routesRoutes)
	server := NewServer(cfg, log, databaseDatabase, cacheCache, routerRouter)
	return server
}
